rdv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rendezvous.urls')),
    path('rendezvous/', include('rendezvous.urls')),
    path('patients/', include('patients.urls')),
    path('users/', include('users.urls')),
]

rendezvous/urls.py
from django.urls import path
from rendezvous import views

urlpatterns = [
    path('', views.index),
    path('index', views.index),
    path('feed', views.feed),
    path('add', views.add),
    path('edit/<int:id>', views.edit),
    path('delete/<int:id>', views.delete)
]

rdv/models.py
from ast import alias
from django.db import models

class Patients(models.Model) :
    id = models.AutoField(primary_key=True)
    prenom = models.CharField(max_length=50)
    nom = models.CharField(max_length=50)
    cin = models.CharField(max_length=10)
    email = models.EmailField(max_length=255, blank=True)
    telephone = models.CharField(max_length=10, blank=True)
    date_naissance = models.DateField(null=True, blank=True)

class Rendezvous(models.Model) :
    id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey(Patients, on_delete=models.CASCADE)
    date_heure = models.DateTimeField()
    duree = models.IntegerField()
    remarque = models.TextField(blank=True)

rendezvous/forms.py
from django.forms import ModelForm
from rdv.models import Rendezvous
from django import forms

class RendezvousForm (ModelForm):
    patient_id = forms.IntegerField(error_messages={'required': 'Obligatoire'})
    date_heure = forms.DateTimeField(error_messages={'required': 'Obligatoire'})
    duree = forms.IntegerField(error_messages={'required': 'Obligatoire'})

    class Meta:
        model = Rendezvous
        fields = ('date_heure', 'duree', 'remarque')

rendezvous/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db import connection
from django.conf import settings
from http.client import HTTPResponse
import datetime
from json import JSONEncoder
from rdv.models import Rendezvous, Patients
from .forms import RendezvousForm

@login_required
def index(request):
    context = {
        'conn': connection,
        'debug': settings.DEBUG
    }
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        context['layout'] = 'layouts/ajax.html'
    else:
        context['layout'] = 'layouts/default.html'
        context['tab'] = 'rendezvous'

    return render(request, 'Rendezvous/index.html', context)

@login_required
def feed(request):
    start = request.GET.get('start')
    end = request.GET.get('end')

    q = Rendezvous.objects.all().filter(date_heure__gte=start)
    q.filter(date_heure__lte=end)
    
    data = []
    for rendezvous in Rendezvous.objects.all():
        data.append({
            "id": rendezvous.id,
            "title": rendezvous.patient_id.prenom + ' ' + rendezvous.patient_id.nom,
            "start": rendezvous.date_heure,
            "end": rendezvous.date_heure + datetime.timedelta(minutes=rendezvous.duree)
        })

    return JsonResponse(data, safe=False)

@login_required
def add(request):
    context = {}
    if request.method == 'POST':
        form = RendezvousForm(request.POST)
        if form.is_valid():
            rendezvous = form.save(commit=False)
            rendezvous.patient_id = Patients.objects.filter(id=request.POST.get('patient_id'))[0]
            rendezvous.save()
            return redirect('/rendezvous')
        else:
            context['error_message'] = 'Rendez-vous n’a pas pu être ajouté! Veuillez réessayer.'
    else:
        start = request.GET.get('start')
        end = request.GET.get('end')
        defaults = {}
        if start and end:
            dt_start = datetime.datetime.strptime(start, '%Y-%m-%dT%H:%M:%S.000Z')
            dt_end = datetime.datetime.strptime(end, '%Y-%m-%dT%H:%M:%S.000Z')
            timedelta = dt_end - dt_start
            defaults = {
                "date_heure": dt_start,
                "duree": int(timedelta.total_seconds() / 60)
            }
        form = RendezvousForm(initial=defaults)

    context['form'] = form
    context['patients'] = Patients.objects.all()

    return render(request, 'Rendezvous/add.html', context)

@login_required
def edit(request, id):
    rendezvous = get_object_or_404(Rendezvous, pk=id)
    form = RendezvousForm(request.POST or None, instance=rendezvous, initial={'patient_id': rendezvous.patient_id.id})
    context = {}

    if request.method == 'POST':
        if form.is_valid():
            rendezvous = form.save(commit=False)
            rendezvous.patient_id = Patients.objects.filter(id=request.POST.get('patient_id'))[0]
            rendezvous.save()
            return redirect('/rendezvous')
        else:
            context['error_message'] = 'Rendez-vous n’a pas pu être modifié! Veuillez réessayer.'

    context['form'] = form
    context['patients'] = Patients.objects.all()
    context['rendezvous_id'] = id

    return render(request, 'Rendezvous/edit.html', context)

@login_required
def delete(request, id):
    rendezvous = get_object_or_404(Rendezvous, pk=id)
    rendezvous.delete()
    return redirect('/rendezvous')

templates/Rendezvous/_form.html
<!-- Le message Flash : -->
{% if error_message %}
<div class="alert alert-danger alert-dismissible d-flex align-items-center" role="alert">
    <i class="bi-x-circle-fill"></i>&nbsp;
    {{ error_message }}   
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<!-- Les zones de saisie : -->
<div class="mb-3">
    <label for="id_patient_id" class="form-label">Patient</label>
    <select name="patient_id" class="form-control select2{% if form.patient_id.errors %} is-invalid{% endif %}" id="id_patient_id">
        <option value="">&nbsp;</option>
    {% for patient in patients %}
        <option value="{{ patient.id }}" {% if form.patient_id.value == patient.id %} selected{% endif %}>{{ patient.prenom }}, {{ patient.nom }} ({{ patient.cin }})</option>
    {% endfor %}
    </select>
    {% for error in form.patient_id.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="mb-3">
    <label for="id_date_heure" class="form-label">Date &amp; heure</label>
    <input type="datetime-local" name="date_heure" class="form-control{% if form.date_heure.errors %} is-invalid{% endif %}" value="{{ form.date_heure.value|date:'Y-m-d\TH:i' }}" id="id_date_heure">
    {% for error in form.date_heure.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="mb-3">
    <label for="id_duree" class="form-label">Durée (minutes)</label>
    <input type="number" name="duree" class="form-control{% if form.duree.errors %} is-invalid{% endif %}" value="{{ form.duree.value|default_if_none:'' }}" id="id_duree">
    {% for error in form.duree.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="mb-3">
    <label for="id_remarque" class="form-label">Remarque</label>
    <textarea name="remarque" class="form-control{% if form.remarque.errors %} is-invalid{% endif %}" id="id_remarque" rows="5">{{ form.remarque.value|default_if_none:'' }}</textarea>
    {% for error in form.remarque.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>

templates/Rendezvous/add.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Nouveau rendez-vous</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post" action="{{ request.get_full_path }}" novalidate>
        {% csrf_token %}
        <div class="modal-body">
            {% include "Rendezvous/_form.html" %}            
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary float-start" data-bs-dismiss="modal"><i class="bi-arrow-counterclockwise"></i> Annuler</button>
            <button type="submit" class="btn btn-primary float-end"><i class="bi-save"></i> Enregistrer</button>
        </div>
        </form>
    </div>
</div>

templates/Rendezvous/edit.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editer rendez-vous</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post" action="{{ request.get_full_path }}" novalidate>
        {% csrf_token %}
        <div class="modal-body">
            {% include "Rendezvous/_form.html" %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="bi-arrow-counterclockwise"></i> Annuler</button>
            <button type="submit" class="btn btn-primary"><i class="bi-save"></i> Enregistrer</button>
        </div>
        </form>
        <div style="margin: -55px 0 15px 15px; width: 150px">
            <form method="post" accept-charset="utf-8" action="/rendezvous/delete/{{ rendezvous_id }}">
            {% csrf_token %}
            <button type="button" class="btn btn-danger" onclick="var form = $(this).closest('form'); bootbox.confirm({title: 'Confirmation', message: $(this).data('confirm'), callback: function(r){ if (r) form.submit(); }});" data-confirm="Êtes-vous sûrs de vouloir supprimer ce rendez-vous ?">
                <i class="bi-trash-fill"></i> Supprimer
            </button>
            </form>
        </div>
    </div>
</div>

templates/Rendezvous/index.html
{% extends layout %}
{% load helper %}

{% block title %}Rendez-vous{% endblock %}
{% block css %}
<link href="//cdn.jsdelivr.net/npm/fullcalendar@5.9.0/main.min.css" rel="stylesheet">
<link href="/static/css/rendezvous_index.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="rendezvous index content xcrud-main">
    <div class="mb-3 clearfix">
        <h3 class="float-start">Gestion des rendez-vous</h3>
        <div class="alert alert-info float-end mb-0 py-2 small">
            <i class="bi-info-circle-fill"></i>&nbsp;
            Cliquez sur une plage de cellules du calendrier pour créer un rendez-vous
        </div>
    </div>
    <div id="calendar"></div>
</div>
{% endblock %}
{% block script %}
<script src="//cdn.jsdelivr.net/npm/fullcalendar@5.9.0/main.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/fullcalendar@5.9.0/locales-all.min.js"></script>
<script src="/static/js/rendezvous_index.js"></script>
{% endblock %}