patients/urls.py
from django.urls import path, include
from django.urls.resolvers import URLPattern
from patients import views

urlpatterns = [
    path('', views.index),
    path('index', views.index),
    path('add', views.add),
    path('edit/<int:id>', views.edit),
    path('delete/<int:id>', views.delete)
]

rdv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rendezvous.urls')),
    path('rendezvous/', include('rendezvous.urls')),
    path('patients/', include('patients.urls')),
    path('users/', include('users.urls')),
]

rdv/models.py
from ast import alias
from django.db import models

class Patients(models.Model) :
    id = models.AutoField(primary_key=True)
    prenom = models.CharField(max_length=50)
    nom = models.CharField(max_length=50)
    cin = models.CharField(max_length=10)
    email = models.EmailField(max_length=255, blank=True)
    telephone = models.CharField(max_length=10, blank=True)
    date_naissance = models.DateField(null=True, blank=True)

class Rendezvous(models.Model) :
    id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey(Patients, on_delete=models.CASCADE)
    date_heure = models.DateTimeField()
    duree = models.IntegerField()
    remarque = models.TextField(blank=True)

patients/forms.py
from django.forms import ModelForm
from rdv.models import Patients
from django import forms

class PatientForm (ModelForm):
    prenom = forms.CharField(error_messages={'required': 'Obligatoire'})
    nom = forms.CharField(error_messages={'required': 'Obligatoire'})
    cin = forms.CharField(error_messages={'required': 'Obligatoire'})

    class Meta:
        model = Patients
        fields = '__all__'
        labels = {
            'nom': 'Nom',
            'prenom': 'Prénom',
            'cin': 'CIN',
            'email': 'E-mail',
            'telephone': 'Téléphone',
            'date_naissance': 'Date de naissance',
        }

patients/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import connection
from django.conf import settings
from rdv.models import Patients
from .forms import PatientForm

@login_required
def index(request):
    # Ordre :
    order_by = request.GET.get('sort', 'nom')
    queryset = Patients.objects.all().order_by(order_by)

    # Pagination :
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'order_by': order_by,
        'conn': connection,
        'debug': settings.DEBUG
    }
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        context['layout'] = 'layouts/ajax.html'
    else:
        context['layout'] = 'layouts/default.html'
        context['tab'] = 'patients'

    return render(request, 'Patients/index.html', context)

@login_required
def add(request):
    context = {}
    if request.method == 'POST':
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/patients')
        else:
            context['error_message'] = 'Patient n’a pas pu être ajouté! Veuillez réessayer.'
    else:
        form = PatientForm()
    context['form'] = form

    return render(request, 'Patients/add.html', context)

@login_required
def edit(request, id):
    patient = get_object_or_404(Patients, pk=id)
    form = PatientForm(request.POST or None, instance=patient)
    context = {}

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/patients')
        else:
            context['error_message'] = 'Patient n’a pas pu être modifié! Veuillez réessayer.'

    context['form'] = form

    return render(request, 'Patients/edit.html', context)

@login_required
def delete(request, id):
    patient = get_object_or_404(Patients, pk=id)
    patient.delete()
    return redirect('/patients')

templates/Patients/_form.html
<!-- Le message Flash : -->
{% if error_message %}
<div class="alert alert-danger alert-dismissible d-flex align-items-center" role="alert">
    <i class="bi-x-circle-fill"></i>&nbsp;
    {{ error_message }}   
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<!-- Les zones de saisie : -->
<div class="mb-3">
    <label for="id_prenom" class="form-label">Prénom</label>
    <input type="text" name="prenom" class="form-control{% if form.prenom.errors %} is-invalid{% endif %}" value="{{ form.prenom.value|default_if_none:'' }}" id="id_prenom">
    {% for error in form.prenom.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="mb-3">
    <label for="id_nom" class="form-label">Nom</label>
    <input type="text" name="nom" class="form-control{% if form.nom.errors %} is-invalid{% endif %}" value="{{ form.nom.value|default_if_none:'' }}" id="id_nom">
    {% for error in form.nom.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="mb-3">
    <label for="id_cin" class="form-label">CIN (Si mineur mettre celui du titeur)</label>
    <input type="text" name="cin" class="form-control{% if form.cin.errors %} is-invalid{% endif %}" value="{{ form.cin.value|default_if_none:'' }}" id="id_cin">
    {% for error in form.cin.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="mb-3">
    <label for="id_email" class="form-label">E-mail</label>
    <input type="email" name="email" class="form-control{% if form.email.errors %} is-invalid{% endif %}" value="{{ form.email.value|default_if_none:'' }}" id="id_email">
    {% for error in form.email.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="mb-3">
    <label for="id_telephone" class="form-label">Téléphone</label>
    <input type="text" name="telephone" class="form-control{% if form.telephone.errors %} is-invalid{% endif %}" value="{{ form.telephone.value|default_if_none:'' }}" id="id_telephone">
    {% for error in form.telephone.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="mb-3">
    <label for="id_date_naissance" class="form-label">Date naissance</label>
    <input type="date" name="date_naissance" class="form-control{% if form.date_naissance.errors %} is-invalid{% endif %}" value="{{ form.date_naissance.value|date:'Y-m-d' }}" id="id_date_naissance">
    {% for error in form.date_naissance.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>

templates/Patients/add.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Nouveau patient</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post" action="{{ request.get_full_path }}" novalidate>
        {% csrf_token %}
        <div class="modal-body">
            {% include "Patients/_form.html" %}            
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary float-start" data-bs-dismiss="modal"><i class="bi-arrow-counterclockwise"></i> Annuler</button>
            <button type="submit" class="btn btn-primary float-end"><i class="bi-save"></i> Enregistrer</button>
        </div>
        </form>
    </div>
</div>

templates/Patients/edit.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editer patient</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post" action="{{ request.get_full_path }}" novalidate>
        {% csrf_token %}
        <div class="modal-body">
            {% include "Patients/_form.html" %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary float-start" data-bs-dismiss="modal"><i class="bi-arrow-counterclockwise"></i> Annuler</button>
            <button type="submit" class="btn btn-primary float-end"><i class="bi-save"></i> Enregistrer</button>
        </div>
        </form>
    </div>
</div>

templates/Patients/index.html
{% extends layout %}
{% load helper %}

{% block title %}Patients{% endblock %}
{% block css %}
{% endblock %}

{% block content %}
<div class="patients index content xcrud-main">
    <h3>Gestion des patients</h3>

    <div class="clearfix" style="margin-bottom: 10px">
        <a href="/patients/add" class="btn btn-success xcrud-btn-add float-end"><i class="bi-person-plus-fill"></i> Nouveau patient</a>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="sorting xcrud-sort" style="width: 15%;">{% paginator_sort request 'prenom' 'Prénom' %}</th>
                    <th class="sorting xcrud-sort" style="width: 15%;">{% paginator_sort request 'nom' 'Nom' %}</th>
                    <th class="sorting xcrud-sort" style="width: 10%;">{% paginator_sort request 'cin' 'CIN' %}</th>
                    <th class="sorting xcrud-sort">{% paginator_sort request 'email' 'E-mail' %}</th>
                    <th class="sorting xcrud-sort" style="width: 12%;">{% paginator_sort request 'telephone' 'Téléphone' %}</th>
                    <th class="sorting xcrud-sort" style="width: 15%;">{% paginator_sort request 'date_naissance' 'Date naissance' %}</th>
                    <th class="actions" style="width: 8%;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for patient in page_obj %}
                <tr>
                    <td>{{ patient.prenom }}</td>
                    <td>{{ patient.nom }}</td>
                    <td>{{ patient.cin }}</td>
                    <td>{{ patient.email }}</td>
                    <td>{{ patient.telephone }}</td>
                    <td>{{ patient.date_naissance|date:'Y-m-d' }}</td>
                    <td class="actions">
                        <a href="/patients/edit/{{ patient.id }}" class="btn btn-warning btn-sm xcrud-btn-edit" data-bs-toggle="tooltip" title="Éditer"><i class="bi-pencil-fill"></i></a>
                        <a href="/patients/delete/{{ patient.id }}" class="btn btn-danger btn-sm xcrud-btn-delete" data-bs-toggle="tooltip" title="Supprimer" data-msg="Êtes-vous sûrs de vouloir supprimer le patient `{{ patient.prenom }} {{ patient.nom }}` ?"><i class="bi-x-lg"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Pagination: -->
    {% include "elements/paginator.html" %}

    <!-- Log SQL: -->
    {% if debug %}{% include "elements/sql_dump.html" %}{% endif %}
</div>
{% endblock %}