rdv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rendezvous.urls')),
    path('rendezvous/', include('rendezvous.urls')),
    path('patients/', include('patients.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', views.index),
    path('index', views.index),
    path('login', LoginView.as_view(template_name='users/login.html', next_page='/')),
    path('logout', LogoutView.as_view(next_page='/users/login')),
    path('add', views.add),
    path('edit/<int:id>', views.edit),
    path('delete/<int:id>', views.delete)
]

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms

class UserForm (ModelForm):
    username = forms.CharField(error_messages={'required': 'Obligatoire', 'unique': 'Un utilisateur avec ce pseudo existe déjà'})
    password = forms.CharField(error_messages={'required': 'Obligatoire'})
    email = forms.CharField(error_messages={'required': 'Obligatoire'})
    first_name = forms.CharField(error_messages={'required': 'Obligatoire'})
    last_name = forms.CharField(error_messages={'required': 'Obligatoire'})
    date_joined = forms.DateField(error_messages={'required': 'Obligatoire'})

    class Meta:
        model = User
        fields = '__all__'

users/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import connection
from django.conf import settings
from django.contrib.auth.models import User
from .forms import UserForm

@login_required
def index(request):
    # Ordre :
    order_by = request.GET.get('sort', 'last_name')
    queryset = User.objects.all().order_by(order_by)

    # Pagination :
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'order_by': order_by,
        'conn': connection,
        'debug': settings.DEBUG
    }
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        context['layout'] = 'layouts/ajax.html'
    else:
        context['layout'] = 'layouts/default.html'
        context['tab'] = 'users'

    return render(request, 'Users/index.html', context)

@login_required
def add(request):
    context = {}
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/users')
        else:
            context['error_message'] = 'Utilisateur n’a pas pu être ajouté! Veuillez réessayer.'
    else:
        form = UserForm()
    context['form'] = form

    return render(request, 'Users/add.html', context)

@login_required
def edit(request, id):
    user = get_object_or_404(User, pk=id)
    form = UserForm(request.POST or None, instance=user)
    context = {}

    if request.method == 'POST':
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(request.POST.get('password'))
            user.is_active = True
            user.save()
            return redirect('/users')
        else:
            context['error_message'] = 'Utilisateur n’a pas pu être modifié! Veuillez réessayer.'
            print(form.errors)

    context['form'] = form

    return render(request, 'Users/edit.html', context)

@login_required
def delete(request, id):
    user = get_object_or_404(User, pk=id)
    user.delete()
    return redirect('/users')

templates/Users/_form.html
<!-- Le message Flash : -->
{% if error_message %}
<div class="alert alert-danger alert-dismissible d-flex align-items-center" role="alert">
    <i class="bi-x-circle-fill"></i>&nbsp;
    {{ error_message }}   
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<!-- Les zones de saisie : -->
<div class="row">
    <div class="col">
        <div class="mb-3">
            <label for="id_first_name" class="form-label">Prénom</label>
            <input type="text" name="first_name" class="form-control{% if form.first_name.errors %} is-invalid{% endif %}" value="{{ form.first_name.value|default_if_none:'' }}" id="id_first_name">
            {% for error in form.first_name.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
        </div>
    </div>
    <div class="col">
        <div class="mb-3">
            <label for="id_last_name" class="form-label">Nom</label>
            <input type="text" name="last_name" class="form-control{% if form.last_name.errors %} is-invalid{% endif %}" value="{{ form.last_name.value|default_if_none:'' }}" id="id_last_name">
            {% for error in form.last_name.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
        </div>
    </div>
</div>
<div class="mb-3">
    <label for="id_email" class="form-label">E-mail</label>
    <input type="email" name="email" class="form-control{% if form.email.errors %} is-invalid{% endif %}" value="{{ form.email.value|default_if_none:'' }}" id="id_email">
    {% for error in form.email.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>
<div class="row">
    <div class="col">
        <div class="mb-3">
            <label for="id_username" class="form-label">Nom d’utilisateur</label>
            <input type="text" name="username" class="form-control{% if form.username.errors %} is-invalid{% endif %}" value="{{ form.username.value|default_if_none:'' }}" id="id_username">
            {% for error in form.username.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
        </div>
    </div>
    <div class="col">
        <div class="mb-3">
            <label for="id_password" class="form-label">Mot de passe</label>
            <input type="password" name="password" class="form-control{% if form.password.errors %} is-invalid{% endif %}" value="" id="id_password">
            {% for error in form.password.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
        </div>
    </div>
</div>
<div class="mb-3">
    <label for="id_date_joined" class="form-label">Date d’arrivée</label>
    <input type="date" name="date_joined" class="form-control{% if form.date_joined.errors %} is-invalid{% endif %}" value="{{ form.date_joined.value|date:'Y-m-d' }}" id="id_date_joined">
    {% for error in form.date_joined.errors %}<div class="invalid-feedback">{{ error }}</div>{% endfor %}
</div>

templates/Users/add.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Nouvel utilisateur</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post" action="{{ request.get_full_path }}" novalidate>
        {% csrf_token %}
        <div class="modal-body">
            {% include "Users/_form.html" %}            
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary float-start" data-bs-dismiss="modal"><i class="bi-arrow-counterclockwise"></i> Annuler</button>
            <button type="submit" class="btn btn-primary float-end"><i class="bi-save"></i> Enregistrer</button>
        </div>
        </form>
    </div>
</div>

templates/Users/edit.html
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Editer utilisateur</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form method="post" action="{{ request.get_full_path }}" novalidate>
        {% csrf_token %}
        <div class="modal-body">
            {% include "Users/_form.html" %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary float-start" data-bs-dismiss="modal"><i class="bi-arrow-counterclockwise"></i> Annuler</button>
            <button type="submit" class="btn btn-primary float-end"><i class="bi-save"></i> Enregistrer</button>
        </div>
        </form>
    </div>
</div>

templates/Users/index.html
{% extends layout %}
{% load helper %}

{% block title %}Utilisateurs{% endblock %}
{% block css %}
{% endblock %}

{% block content %}
<div class="patients index content xcrud-main">
    <h3>Gestion des utilisateurs</h3>

    <div class="clearfix" style="margin-bottom: 10px">
        <a href="/users/add" class="btn btn-success xcrud-btn-add float-end"><i class="bi-person-plus-fill"></i> Nouvel utilisateur</a>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="sorting xcrud-sort" style="width: 15%;">{% paginator_sort request 'first_name' 'Prénom' %}</th>
                    <th class="sorting xcrud-sort" style="width: 15%;">{% paginator_sort request 'last_name' 'Nom' %}</th>
                    <th class="sorting xcrud-sort">{% paginator_sort request 'email' 'E-mail' %}</th>
                    <th class="sorting xcrud-sort" style="width: 12%;">{% paginator_sort request 'username' 'Nom d’utilisateur' %}</th>
                    <th class="sorting xcrud-sort" style="width: 15%;">{% paginator_sort request 'date_joined' 'Date d’arrivée' %}</th>
                    <th class="actions" style="width: 8%;">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for user in page_obj %}
                <tr>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.date_joined|date:'Y-m-d' }}</td>
                    <td class="actions">
                        <a href="/users/edit/{{ user.id }}" class="btn btn-warning btn-sm xcrud-btn-edit" data-bs-toggle="tooltip" title="Éditer"><i class="bi-pencil-fill"></i></a>
                        <a href="/users/delete/{{ user.id }}" class="btn btn-danger btn-sm xcrud-btn-delete" data-bs-toggle="tooltip" title="Supprimer" data-msg="Êtes-vous sûrs de vouloir supprimer l’utilisateur `{{ user.first_name }} {{ user.last_name }}` ?"><i class="bi-x-lg"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Pagination: -->
    {% include "elements/paginator.html" %}

    <!-- Log SQL: -->
    {% if debug %}{% include "elements/sql_dump.html" %}{% endif %}
</div>
{% endblock %}

templates/Users/login.html
{% extends 'layouts/login.html' %}
{% block content %}

{% if form.errors %}
<div class="alert alert-danger alert-dismissible d-flex align-items-center text-start" role="alert">
    <i class="bi-x-circle-fill"></i>&nbsp;
    Nom d’utilisateur ou mot de passe incorrecte!
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
<form method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Veuillez vous connecter</h1>

    <div class="form-floating">
        <input type="text" class="form-control" name="username" id="floatingEmail" placeholder="Nom d’utilisateur">
        <label for="floatingEmail">Nom d’utilisateur</label>
    </div>
    <div class="form-floating">
        <input type="password" class="form-control" name="password" id="floatingPassword" placeholder="Mot de passe">
        <label for="floatingPassword">Mot de passe</label>
    </div>

    <div class="checkbox mb-3">
        <label>
            <input type="checkbox" value="remember-me"> Se souvenir de moi
        </label>
    </div>
    <button type="submit" class="w-100 btn btn-lg btn-primary">Se connecter</button>

    <p class="mt-5 mb-3 text-muted">&copy; {% now 'Y' %} Tous droits réservés.</p>
</form>
{% endblock %}